name: Publish Python distributions to PyPI and TestPyPI

on: release

jobs:
  build-and-publish:
    name: Build and publish Python distributions to PyPI and TestPyPI
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build a binary wheel and a source tarball
      run: |
        python -m pip install --upgrade pip
        pip install build --user
        python -m build --sdist --wheel --outdir dist/ .

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
